
export default function head() {
    return (
          <>
           <title>Pricing-Ui</title>
           <meta content="width=device-width ,initial-scale=1" name="viewport"/>
           <meta name="description" content="Generated by next app"/>
           {/* <link rel="icon" href="/Logo.png"/> */}
          </>
    )
  }
  